# Generated by Django 4.0.4 on 2022-05-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0008_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.AddField(
            model_name='usuario',
            name='receive_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
