# Generated by Django 4.0.4 on 2022-05-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0009_delete_cliente_usuario_receive_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='clave',
        ),
    ]
