# Generated by Django 4.0.4 on 2022-05-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0011_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
