# Generated by Django 4.0.4 on 2022-05-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0014_alter_usuario_receive_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='receive_newsletter',
            field=models.BooleanField(blank=True),
        ),
    ]
