# Generated by Django 4.0.4 on 2022-05-10 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0015_alter_usuario_receive_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='clasificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion1.clasificacion'),
        ),
    ]
