# Generated by Django 4.0.4 on 2022-05-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0019_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='respuesta',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
