# Generated by Django 4.0.4 on 2022-05-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0020_pregunta_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='mensaje',
            field=models.TextField(max_length=500),
        ),
    ]
