# Generated by Django 4.0.4 on 2022-05-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0021_producto_imagen_alter_mensaje_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='logo.png', null=True, upload_to='foto_prod'),
        ),
    ]
