# Generated by Django 4.0.4 on 2022-05-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0023_orden_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
            preserve_default=False,
        ),
    ]
