# Generated by Django 4.0.4 on 2022-05-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0028_order_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(help_text='identifica al producto: ej Prod1 '),
        ),
    ]
